In [2]:
import numpy as np

### Data Types
    the dtypes are available as np.bool_, np.float32, etc.

lets see an example for data type float

In [4]:
x = np.float(1)
x

1.0

In [7]:
x = np.float([1.2,3.4])
x

TypeError: float() argument must be a string or a number, not 'list'

OOPS we just had an error
lets look how to solve it!! Solution for this is using np.float_()

In [8]:
x = np.float_([1.2,1.3])
x

array([1.2, 1.3])

In [9]:
# and there we see that now we can pass a list of float

In [10]:
x = np.int_([1,3,4])
x

array([1, 3, 4])

In [11]:
# Creating a array
x = np.array([2,3,1,0])
x

array([2, 3, 1, 0])

arange(): will create arrays with regularly incrementing values. Check the docstring for complete information on the various ways it can be used. A few examples will be given here:

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# There are chances when we convert list of data into array to push it into machine learning model

In [14]:
list_ = [1,23,45,64]
convert_list_to_array = np.asarray(list_)
convert_list_to_array

array([ 1, 23, 45, 64])