In [3]:
import numpy as np

<img src="https://miro.medium.com/max/854/1*56Zr8V9k_5Wr3ctJi3wRyw.png"> 

### Data Types
    the dtypes are available as np.bool_, np.float32, etc.

lets see an example for data type float

In [4]:
x = np.float(1)
x

1.0

In [7]:
x = np.float([1.2,3.4])
x

TypeError: float() argument must be a string or a number, not 'list'

OOPS we just had an error
lets look how to solve it!! Solution for this is using np.float_()

In [8]:
x = np.float_([1.2,1.3])
x

array([1.2, 1.3])

In [9]:
# and there we see that now we can pass a list of float

In [10]:
x = np.int_([1,3,4])
x

array([1, 3, 4])

In [11]:
# Creating a array
x = np.array([2,3,1,0])
x

array([2, 3, 1, 0])

arange(): will create arrays with regularly incrementing values. Check the docstring for complete information on the various ways it can be used. A few examples will be given here:

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# There are chances when we convert list of data into array to push it into machine learning model

In [14]:
list_ = [1,23,45,64]
convert_list_to_array = np.asarray(list_)
convert_list_to_array

array([ 1, 23, 45, 64])

In [16]:
## Getting shape of a image
convert_list_to_array.shape

(4,)

In [17]:
# indexing

In [19]:
x = np.array([1,2,3,4])
x[1]

2

In [21]:
### As we can see that it prints the value in index 1. just as a normal array the index starts from 0.

In [22]:
x = np.array([('Abhishek', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [23]:
x

array([('Abhishek', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [24]:
x[1]

('Fido', 3, 27.)

In [1]:
# Mutliplicatin of two matrix

In [4]:
array_1 = np.array([1,2,4,5])
array_2 = np.array([6,7,8,9])
array_1*array_2

array([ 6, 14, 32, 45])

In [5]:
# Reshaping a matrix

In [6]:
array_1.shape

(4,)

In [8]:
array_1 = array_1.reshape(4,1)
array_1.shape

(4, 1)